### PR TITLE
Complete IFCT data in JSON and CSV file formats

### PR DESCRIPTION
**Pull request by nithyamani**
Please consider this pull request that includes the entire Indian Food Composition Table data available in PDF format at http://www.ifct2017.com/frame.php?page=food, now made available in CSV and JSON formats. Hope it will be helpful for many people.

### CODE REVIEW

**Comment by wolfram77** [comment]
@nithyamani You obviously generated this with a script. It is useful to checkin that, instead of CSV and JSON generated files. We currently have `index.csv` which is generated using `assets/` with `build.js`. How about integrating there? Accordingly we can replace index.csv with the one you are generating. I also note we are missing some columns in the generated CSV. Using self-describing columns is definitely a good readability fix, when working with spreadsheet.

**Comment by nithyamani** [comment]
@wolfram77 I have checked in the Python scripts that I used to generate the JSON format for the IFCT table. Please let me know the missing columns in the generated CSV. I'll try fixing it whenever possible. Thanks!

**Comment by wolfram77** [comment]
@nithyamani To keep the project manageable, i hope to stick to JS. If its okay, i will go through your script and update your pull request, such that it updates `index.csv` (or similar) with appropriate headings. Is +- error attached to a single column as you have done, readable by Google sheets? Also i dont think JSON is a suitable format for tabular data. Lets stick to CSV.

**Comment by nithyamani** [comment]
@wolfram77 Please feel free to make your own decision on merging these changes into your repo. I prepared the JSON format for my own requirement and thought if I share it, it would also be useful for someone having similar requirements. Thanks!

**Comment by wolfram77** [comment]
Original commits:

```
SHA: b4c250134631521a46fc9f15805f4669ea241c37
Complete IFCT data in JSON and CSV file formats
```

```
SHA: c3d38e222caeb2375fb07e359ea1f3f3b1871284
Python scripts used to generate the JSON format IFCT data (IndianFoodCompositionTable_In_JSON_Format_With_Objectid_And_RegionalNames.json)

1_food_index_from_IFCT_as_csv.py reads the content from page # 539 to page #572 (INDEX) in the IFCT PDF file and stores them in a .csv file
    INPUT: IFCT.PDF
   OUTPUT: regionalNames.csv
2_group_food_regional_names_by_code.py processes the input file regionalNames.csv that was generated by the script 1_food_index_from_IFCT_as_csv.py and groups the regional food names by the food code 
   INPUT: regionalNames.csv 
   OUTPUT: regionalFoodNamesOrderedByCode.csv
3_convert_IFCT_csv_format_to_json.py processes the input .csv file IndianFoodCompositionTable_In_CSV_Format.csv that was generated manually by consolidating the .csv file available at https://github.com/ifct2017/compositions/tree/master/assets and converts it into JSON format
   INPUT: IndianFoodCompositionTable_In_CSV_Format.csv
  OUTPUT: IndianFoodCompositionTable_In_JSON_Format.json
4_append_food_regional_names_in_json finds the respective regional food names from the input file regionalFoodNamesOrderedByCode.csv (generated by 2_group_food_regional_names_by_code.py) and appends the additional details in the given IndianFoodCompositionTable_In_JSON_Format.json file (generated by the script 3_convert_IFCT_csv_format_to_json.py)
  INPUT: regionalFoodNamesOrderedByCode.csv & IndianFoodCompositionTable_In_JSON_Format.json
  OUTPUT: IndianFoodCompositionTable_In_JSON_Format_With_Sorted_RegionalNames.json
```

```
SHA: 9010e990779cdbe1f181b84e0e4e9e6416368651
All resources used in the python scripts
```

**Comment by wolfram77** [comment]
@nithyamani Is there a way to represent measurement error in a single cell along with the number in Google Sheets? Using unicode plus-minus symbol does not seem to work.

image

**Comment by wolfram77** [comment]
I have separated out the measurement error into a separate column.
https://docs.google.com/spreadsheets/d/19C2EB4PIMgyusqKOnBq4-aBQxLjCai1Zg45YcBNTzFo/edit?usp=sharing

**Pull request merged**
